[project]
name = "holoplus-to-discord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "secretstorage>=3.5.0",
    "yt-dlp>=2025.12.8",
]
